# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/postseam/example/v1/store_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb.postseam.example.v1 import store_pb2 as pb_dot_postseam_dot_example_dot_v1_dot_store__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*pb/postseam/example/v1/store_service.proto\x12\x16pb.postseam.example.v1\x1a\"pb/postseam/example/v1/store.proto\"F\n\x12\x43reateStoreRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x15\n\rbusiness_name\x18\x03 \x01(\t\"#\n\x0fGetStoreRequest\x12\x10\n\x08store_id\x18\x01 \x01(\t2\xc0\x01\n\x0cStoreService\x12T\n\x08GetStore\x12\'.pb.postseam.example.v1.GetStoreRequest\x1a\x1d.pb.postseam.example.v1.Store\"\x00\x12Z\n\x0b\x43reateStore\x12*.pb.postseam.example.v1.CreateStoreRequest\x1a\x1d.pb.postseam.example.v1.Store\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.postseam.example.v1.store_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATESTOREREQUEST._serialized_start=106
  _CREATESTOREREQUEST._serialized_end=176
  _GETSTOREREQUEST._serialized_start=178
  _GETSTOREREQUEST._serialized_end=213
  _STORESERVICE._serialized_start=216
  _STORESERVICE._serialized_end=408
# @@protoc_insertion_point(module_scope)
